[package]
name = "seeded_dice_roller"
version = "0.1.0"
edition = "2021"
description = "A dice roller using a seed to give deterministic results."
license = "MIT"

[dependencies]
rand = "0.8.5"
rand_seeder = "0.2.3"
rand_pcg = "0.3.1"
log = "0.4.17"
